volumes:
    api-pictures:
    db-data:

services:
    api:
        container_name: api
        build: .
        ports:
            - "127.0.0.1:8080:80"
        environment:
            - DB_URL=mysql+aiomysql://root:root@db/findteam
            - PICTURE_STORAGE=/pictures
        volumes:
            - api-pictures:/pictures
        restart: "unless-stopped"
        links:
            - db
        networks:
            - default
        
    db:
        container_name: db
        image: mariadb:latest
        restart: "always"
        volumes:
            - db-data:/var/lib/mysql
        ports:
            - "127.0.0.1:3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=findteam
        networks:
            - default