volumes:
    db-data:

services:
    findteam-api:
        container_name: findteam
        build: .
        ports:
            - "127.0.0.1:8080:80"
        environment:
            - DB_URL=mysql+aiomysql://root:root@mariadb/findteam
        restart: "unless-stopped"
        links:
            - db
        networks:
            - default
        
    findteam-mariadb:
        container_name: mariadb
        image: mariadb:latest
        restart: "always"
        volumes:
            - db-data:/var/lib/mysql/data
        ports:
            - "127.0.0.1:3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_MYSQL_DATABASE=findteam
        networks:
            - default